databases:
  - name: remote-db
    databaseName: remote_yaw9
    user: root

services:
  - type: web
    name: remote
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn remote.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: remote_yaw9
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4